### ISSUE TITLE
JS8Call Conflict

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#108] opened 2024-09-02 19:45 UTC
just to be up front, I am running 73 linux on, linux mint on an 11 inch
macbook air.

There is a problem with JS8 call.

If you install it using 73 linux all is ok.

However Synaptic flags it for an upgrade it has the same version number
with an extension, it looks like this 2.2.0+ds-2

If you upgrade it, it will always crash after that.

I think it also messes with WSJTX as well.

The way I fixed it was to use 73 linux to remove both js8 and wspr
packages and then reinstall them.

BR

Chris

**Comment by corvus-ch** [comment] 2024-10-07 13:27
Is there are reason to install WSJTX from source instead from the system package? `Js8call` is also available in the system packages, so what is the benefit of downloading it directly?

**Comment by corvus-ch** [comment] 2024-10-07 13:30
Seems to be a duplicate of #57.

**Comment by km4ack** [comment] 2024-10-14 15:30
And a duplicate of #87. Testing this morning shows that if we install WSJTX from the repo, it might solve the problem. Previously it has been direct download from each site to grab the latest version since the repo is slow to update.

**Closed** 2024-10-14 15:31 UTC
Labels: bug
